#### this file creates login framework for DSLite
#### do not edit this file by hand if you don't know what you are doing
#### Comment sections are being used as signals for start/stop for easy updates

#### Step 1: Loading necessary libraries
library(DSI)
library(DSLite)
library(dsBaseClient)

#### Step 2: Import of mock data files
load(file = here::here("utils/mock_data/demo_obiba", "CNSIM1.rda"))
load(file = here::here("utils/mock_data/demo_obiba", "CNSIM2.rda"))
load(file = here::here("utils/mock_data/demo_obiba", "CNSIM3.rda"))

#### Step 3: Defining the server-side data in a new dslite server
dslite.server <<- DSLite::newDSLiteServer(tables=list(CNSIM1 = study1,
                                                      CNSIM2 = study2,
                                                      CNSIM3 = study3))

#### Step 4: Defining the server-side settings
dslite.server$config(DSLite::defaultDSConfiguration(include=c("dsBase")))
dslite.server$profile()
dslite.server$aggregateMethod("dsListDisclosureSettings")


#### Step 5: Building the logindata object
logindata.dslite.data <- data.frame(server = c("DEMO_OBIBA_1",
                                               "DEMO_OBIBA_2",
                                               "DEMO_OBIBA_3"),
                                    url = "dslite.server",
                                    user = "",
                                    password = "",
                                    table = c("CNSIM1",
                                              "CNSIM2",
                                              "CNSIM3"),
                                    options = list(datashield.privacyControlLevel = "permissive"),
                                    driver = "DSLiteDriver")

#### Step 6: Login to the different DSLite Servers
conns <<- DSI::datashield.login(logindata.dslite.data,
                                assign=TRUE,
                                symbol = "D")

#### Step 7: Cleaning the environment
rm(list = setdiff(ls(), "conns"))
