#### this file creates login framework for DSLite
#### do not edit this file if you don't know what you are doing

#### loading necessary libraries
library(tidyverse)
library(DSI)
library(dsBaseClient)
library(DSLite)

#### Input of mock data rds files
load(file = here::here("utils/mock_data", "CNSIM1.rda"))
load(file = here::here("utils/mock_data", "CNSIM2.rda"))
load(file = here::here("utils/mock_data", "CNSIM3.rda"))

#### apparently rda files are already sorted for correct class type



#### Defining the server-side data
dslite.server <<- DSLite::newDSLiteServer(tables=list(CNSIM1 = study1,
                                                      CNSIM2 = study2,
                                                      CNSIM3 = study3))

#### Defining the server-side packages
dslite.server$config(DSLite::defaultDSConfiguration(include=c("dsBase")))
dslite.server$profile()
dslite.server$aggregateMethod("dsListDisclosureSettings")


#### Building the different DSLite Servers
logindata.dslite.data <- data.frame(server = c("DEMO_OBIBA_1",
                                               "DEMO_OBIBA_2",
                                               "DEMO_OBIBA_3"),
                                    url = c("dslite.server",
                                            "dslite.server",
                                            "dslite.server"),
                                    user = "",
                                    password = "",
                                    table = c("CNSIM1",
                                              "CNSIM2",
                                              "CNSIM3"),
                                    options = list(datashield.privacyControlLevel = "permissive"),
                                    driver = c("DSLiteDriver",
                                               "DSLiteDriver",
                                               "DSLiteDriver"))


#### Login to the different DSLite Servers
conns <<- DSI::datashield.login(logindata.dslite.data,
                                assign=TRUE,
                                symbol = "D")

#### Cleaning the environment
rm(list = setdiff(ls(), "conns"))
