test_that("internal_dependencies_set_dsPackages messages and returns NULL when no dependencies.R exists", {
  project <- withr::local_tempdir()
  testthat::local_mocked_bindings(here = function(...) file.path(project, ...), .package = "here")
  testthat::expect_message(res <- dsAnalysis:::internal_dependencies_set_dsPackages(add = "dsBase", client = "dsBaseClient"),
                           "No dependencies.R found in the project, so it was not updated.")
  testthat::expect_null(res)
  testthat::expect_false(file.exists(file.path(project, "dependencies.R")))
})

test_that("internal_dependencies_set_dsPackages appends a new block at the end of a dependencies.R without a block and without the bot marker", {
  project <- withr::local_tempdir()
  testthat::local_mocked_bindings(here = function(...) file.path(project, ...), .package = "here")
  writeLines(c("library(here)", "library(dplyr)"), file.path(project, "dependencies.R"))
  res <- dsAnalysis:::internal_dependencies_set_dsPackages(add = "dsBase", client = "dsBaseClient")
  lines <- readLines(file.path(project, "dependencies.R"))
  testthat::expect_identical(lines[1:2], c("library(here)", "library(dplyr)"))
  testthat::expect_identical(lines[3], "")
  testthat::expect_true("library(dsBase); library(dsBaseClient)" %in% lines)
  testthat::expect_identical(lines[length(lines) - 1], "library(dsBase); library(dsBaseClient)")
  testthat::expect_identical(res$server, "dsBase")
  testthat::expect_identical(res$client, "dsBaseClient")
  testthat::expect_identical(nrow(res), 1L)
})

test_that("internal_dependencies_set_dsPackages writes a package without a client as a single library() call", {
  project <- withr::local_tempdir()
  testthat::local_mocked_bindings(here = function(...) file.path(project, ...), .package = "here")
  writeLines(c("library(here)"), file.path(project, "dependencies.R"))
  res <- dsAnalysis:::internal_dependencies_set_dsPackages(add = "dsBase", client = "")
  lines <- readLines(file.path(project, "dependencies.R"))
  testthat::expect_true("library(dsBase)" %in% lines)
  testthat::expect_false(any(grepl("library(dsBase);", lines, fixed = TRUE)))
  testthat::expect_identical(res$server, "dsBase")
  testthat::expect_identical(nrow(res), 1L)
})

test_that("internal_dependencies_set_dsPackages inserts a new block before the bot marker line", {
  project <- withr::local_tempdir()
  testthat::local_mocked_bindings(here = function(...) file.path(project, ...), .package = "here")
  bot_marker <- "#### bot-suggest: packages (updated by datashield-analysis-suggest)"
  writeLines(c("library(here)", bot_marker, "library(somethingElse)"), file.path(project, "dependencies.R"))
  dsAnalysis:::internal_dependencies_set_dsPackages(add = "dsSurvival", client = "dsSurvivalClient")
  lines <- readLines(file.path(project, "dependencies.R"))
  marker_line <- which(lines == bot_marker)
  lib_line <- which(lines == "library(dsSurvival); library(dsSurvivalClient)")
  testthat::expect_length(marker_line, 1L)
  testthat::expect_length(lib_line, 1L)
  testthat::expect_true(lib_line < marker_line)
  testthat::expect_identical(lines[1], "library(here)")
  testthat::expect_identical(lines[length(lines)], "library(somethingElse)")
})

test_that("internal_dependencies_set_dsPackages replaces an existing block in place and keeps the lines around it", {
  project <- withr::local_tempdir()
  testthat::local_mocked_bindings(here = function(...) file.path(project, ...), .package = "here")
  writeLines(c("library(here)"), file.path(project, "dependencies.R"))
  dsAnalysis:::internal_dependencies_set_dsPackages(add = "dsBase", client = "dsBaseClient")
  lines_before <- readLines(file.path(project, "dependencies.R"))
  res <- dsAnalysis:::internal_dependencies_set_dsPackages(add = "dsSurvival", client = "dsSurvivalClient")
  lines <- readLines(file.path(project, "dependencies.R"))
  testthat::expect_identical(lines[1], "library(here)")
  testthat::expect_true("library(dsBase); library(dsBaseClient)" %in% lines)
  testthat::expect_true("library(dsSurvival); library(dsSurvivalClient)" %in% lines)
  testthat::expect_identical(nrow(res), 2L)
  testthat::expect_setequal(res$server, c("dsBase", "dsSurvival"))
  testthat::expect_identical(length(lines), length(lines_before) + 1L)
})

test_that("internal_dependencies_set_dsPackages removes a recorded package from the block and from the returned data frame", {
  project <- withr::local_tempdir()
  testthat::local_mocked_bindings(here = function(...) file.path(project, ...), .package = "here")
  writeLines(c("library(here)"), file.path(project, "dependencies.R"))
  dsAnalysis:::internal_dependencies_set_dsPackages(add = c("dsBase", "dsSurvival"), client = c("dsBaseClient", "dsSurvivalClient"))
  res <- dsAnalysis:::internal_dependencies_set_dsPackages(remove = "dsBase")
  lines <- readLines(file.path(project, "dependencies.R"))
  testthat::expect_false("library(dsBase); library(dsBaseClient)" %in% lines)
  testthat::expect_true("library(dsSurvival); library(dsSurvivalClient)" %in% lines)
  testthat::expect_identical(nrow(res), 1L)
  testthat::expect_identical(res$server, "dsSurvival")
})

test_that("internal_dependencies_set_dsPackages re-adding a recorded package updates its client without duplicating the entry", {
  project <- withr::local_tempdir()
  testthat::local_mocked_bindings(here = function(...) file.path(project, ...), .package = "here")
  writeLines(c("library(here)"), file.path(project, "dependencies.R"))
  dsAnalysis:::internal_dependencies_set_dsPackages(add = "dsBase", client = "dsBaseClient")
  res <- dsAnalysis:::internal_dependencies_set_dsPackages(add = "dsBase", client = "")
  lines <- readLines(file.path(project, "dependencies.R"))
  testthat::expect_identical(nrow(res), 1L)
  testthat::expect_identical(res$server, "dsBase")
  testthat::expect_identical(res$client, "")
  testthat::expect_true("library(dsBase)" %in% lines)
  testthat::expect_false("library(dsBase); library(dsBaseClient)" %in% lines)
  testthat::expect_length(which(grepl("library(dsBase", lines, fixed = TRUE)), 1L)
})

test_that("internal_dependencies_set_dsPackages adds several packages at once in the order given", {
  project <- withr::local_tempdir()
  testthat::local_mocked_bindings(here = function(...) file.path(project, ...), .package = "here")
  writeLines(c("library(here)"), file.path(project, "dependencies.R"))
  res <- dsAnalysis:::internal_dependencies_set_dsPackages(add = c("dsBase", "dsSurvival"), client = c("dsBaseClient", ""))
  lines <- readLines(file.path(project, "dependencies.R"))
  testthat::expect_identical(res$server, c("dsBase", "dsSurvival"))
  testthat::expect_identical(res$client, c("dsBaseClient", ""))
  first <- which(lines == "library(dsBase); library(dsBaseClient)")
  second <- which(lines == "library(dsSurvival)")
  testthat::expect_length(first, 1L)
  testthat::expect_length(second, 1L)
  testthat::expect_identical(second, first + 1L)
})

test_that("internal_dependencies_set_dsPackages leaves the file round-trippable so a second call reads back the same packages", {
  project <- withr::local_tempdir()
  testthat::local_mocked_bindings(here = function(...) file.path(project, ...), .package = "here")
  writeLines(c("library(here)"), file.path(project, "dependencies.R"))
  written <- dsAnalysis:::internal_dependencies_set_dsPackages(add = c("dsBase", "dsSurvival"), client = c("dsBaseClient", "dsSurvivalClient"))
  recorded <- dsAnalysis:::internal_dependencies_dsPackages(readLines(file.path(project, "dependencies.R")))
  testthat::expect_identical(recorded$server, c("dsBase", "dsSurvival"))
  testthat::expect_identical(recorded$client, c("dsBaseClient", "dsSurvivalClient"))
  testthat::expect_identical(nrow(recorded), nrow(written))
})

test_that("internal_dependencies_set_dsPackages called with no arguments on a file without a block writes an empty block with only the markers", {
  project <- withr::local_tempdir()
  testthat::local_mocked_bindings(here = function(...) file.path(project, ...), .package = "here")
  writeLines(c("library(here)"), file.path(project, "dependencies.R"))
  res <- dsAnalysis:::internal_dependencies_set_dsPackages()
  lines <- readLines(file.path(project, "dependencies.R"))
  testthat::expect_identical(nrow(res), 0L)
  testthat::expect_identical(lines[1], "library(here)")
  testthat::expect_identical(lines[2], "")
  testthat::expect_length(lines, 4L)
  testthat::expect_false(any(grepl("^library\\(ds", lines)))
  recorded <- dsAnalysis:::internal_dependencies_dsPackages(lines)
  testthat::expect_identical(nrow(recorded), 0L)
})

test_that("internal_dependencies_set_dsPackages removing every recorded package leaves an empty block and keeps the surrounding lines", {
  project <- withr::local_tempdir()
  testthat::local_mocked_bindings(here = function(...) file.path(project, ...), .package = "here")
  writeLines(c("library(here)", "library(dplyr)"), file.path(project, "dependencies.R"))
  dsAnalysis:::internal_dependencies_set_dsPackages(add = c("dsBase", "dsSurvival"), client = c("dsBaseClient", "dsSurvivalClient"))
  res <- dsAnalysis:::internal_dependencies_set_dsPackages(remove = c("dsBase", "dsSurvival"))
  lines <- readLines(file.path(project, "dependencies.R"))
  testthat::expect_identical(nrow(res), 0L)
  testthat::expect_identical(lines[1:2], c("library(here)", "library(dplyr)"))
  testthat::expect_false(any(grepl("dsBase", lines, fixed = TRUE)))
  testthat::expect_false(any(grepl("dsSurvival", lines, fixed = TRUE)))
  testthat::expect_identical(nrow(dsAnalysis:::internal_dependencies_dsPackages(lines)), 0L)
})

test_that("internal_dependencies_set_dsPackages removing a package that was never recorded keeps the block unchanged", {
  project <- withr::local_tempdir()
  testthat::local_mocked_bindings(here = function(...) file.path(project, ...), .package = "here")
  writeLines(c("library(here)"), file.path(project, "dependencies.R"))
  dsAnalysis:::internal_dependencies_set_dsPackages(add = "dsBase", client = "dsBaseClient")
  lines_before <- readLines(file.path(project, "dependencies.R"))
  res <- dsAnalysis:::internal_dependencies_set_dsPackages(remove = "dsMediation")
  lines <- readLines(file.path(project, "dependencies.R"))
  testthat::expect_identical(lines, lines_before)
  testthat::expect_identical(nrow(res), 1L)
  testthat::expect_identical(res$server, "dsBase")
  testthat::expect_identical(res$client, "dsBaseClient")
})

test_that("internal_dependencies_set_dsPackages adds to an existing block without touching lines written after it", {
  project <- withr::local_tempdir()
  testthat::local_mocked_bindings(here = function(...) file.path(project, ...), .package = "here")
  writeLines(c("library(here)"), file.path(project, "dependencies.R"))
  dsAnalysis:::internal_dependencies_set_dsPackages(add = "dsBase", client = "dsBaseClient")
  writeLines(c(readLines(file.path(project, "dependencies.R")), "", "library(trailingPkg)"), file.path(project, "dependencies.R"))
  res <- dsAnalysis:::internal_dependencies_set_dsPackages(add = "dsSurvival", client = "dsSurvivalClient")
  lines <- readLines(file.path(project, "dependencies.R"))
  testthat::expect_identical(lines[1], "library(here)")
  testthat::expect_identical(lines[length(lines)], "library(trailingPkg)")
  testthat::expect_identical(lines[length(lines) - 1], "")
  testthat::expect_identical(nrow(res), 2L)
  testthat::expect_identical(res$server, c("dsBase", "dsSurvival"))
  base_line <- which(lines == "library(dsBase); library(dsBaseClient)")
  surv_line <- which(lines == "library(dsSurvival); library(dsSurvivalClient)")
  testthat::expect_identical(surv_line, base_line + 1L)
})

test_that("internal_dependencies_set_dsPackages replaces the existing block in place and does not insert a second block before the bot marker", {
  project <- withr::local_tempdir()
  testthat::local_mocked_bindings(here = function(...) file.path(project, ...), .package = "here")
  bot_marker <- "#### bot-suggest: packages (updated by datashield-analysis-suggest)"
  writeLines(c("library(here)", bot_marker, "library(somethingElse)"), file.path(project, "dependencies.R"))
  dsAnalysis:::internal_dependencies_set_dsPackages(add = "dsBase", client = "dsBaseClient")
  res <- dsAnalysis:::internal_dependencies_set_dsPackages(add = "dsSurvival", client = "dsSurvivalClient")
  lines <- readLines(file.path(project, "dependencies.R"))
  testthat::expect_identical(nrow(res), 2L)
  testthat::expect_length(which(lines == bot_marker), 1L)
  testthat::expect_identical(lines[1], "library(here)")
  testthat::expect_identical(lines[length(lines)], "library(somethingElse)")
  base_line <- which(lines == "library(dsBase); library(dsBaseClient)")
  surv_line <- which(lines == "library(dsSurvival); library(dsSurvivalClient)")
  testthat::expect_identical(surv_line, base_line + 1L)
  testthat::expect_true(surv_line < which(lines == bot_marker))
  testthat::expect_identical(nrow(dsAnalysis:::internal_dependencies_dsPackages(lines)), 2L)
})

test_that("internal_dependencies_set_dsPackages adding and removing in one call drops the removed package and appends the added one", {
  project <- withr::local_tempdir()
  testthat::local_mocked_bindings(here = function(...) file.path(project, ...), .package = "here")
  writeLines(c("library(here)"), file.path(project, "dependencies.R"))
  dsAnalysis:::internal_dependencies_set_dsPackages(add = c("dsBase", "dsSurvival"), client = c("dsBaseClient", "dsSurvivalClient"))
  res <- dsAnalysis:::internal_dependencies_set_dsPackages(add = "dsMediation", client = "dsMediationClient", remove = "dsBase")
  lines <- readLines(file.path(project, "dependencies.R"))
  testthat::expect_identical(nrow(res), 2L)
  testthat::expect_identical(res$server, c("dsSurvival", "dsMediation"))
  testthat::expect_identical(res$client, c("dsSurvivalClient", "dsMediationClient"))
  testthat::expect_false(any(grepl("dsBase", lines, fixed = TRUE)))
  testthat::expect_true("library(dsMediation); library(dsMediationClient)" %in% lines)
})

test_that("internal_dependencies_set_dsPackages on an empty dependencies.R writes a block preceded by one empty line", {
  project <- withr::local_tempdir()
  testthat::local_mocked_bindings(here = function(...) file.path(project, ...), .package = "here")
  file.create(file.path(project, "dependencies.R"))
  res <- dsAnalysis:::internal_dependencies_set_dsPackages(add = "dsBase", client = "dsBaseClient")
  lines <- readLines(file.path(project, "dependencies.R"))
  testthat::expect_identical(nrow(res), 1L)
  testthat::expect_identical(lines[1], "")
  testthat::expect_length(lines, 4L)
  testthat::expect_identical(lines[3], "library(dsBase); library(dsBaseClient)")
  testthat::expect_identical(dsAnalysis:::internal_dependencies_dsPackages(lines)$server, "dsBase")
})

test_that("internal_dependencies_set_dsPackages keeps the file unchanged when a call adds nothing to an existing empty block", {
  project <- withr::local_tempdir()
  testthat::local_mocked_bindings(here = function(...) file.path(project, ...), .package = "here")
  writeLines(c("library(here)"), file.path(project, "dependencies.R"))
  dsAnalysis:::internal_dependencies_set_dsPackages()
  lines_before <- readLines(file.path(project, "dependencies.R"))
  res <- dsAnalysis:::internal_dependencies_set_dsPackages()
  lines <- readLines(file.path(project, "dependencies.R"))
  testthat::expect_identical(lines, lines_before)
  testthat::expect_identical(nrow(res), 0L)
})
