test_that("internal_dependencies_set_dsPackages messages and returns NULL when no dependencies.R exists", {
  project <- withr::local_tempdir()
  testthat::local_mocked_bindings(here = function(...) file.path(project, ...), .package = "here")
  testthat::expect_message(res <- dsAnalysis:::internal_dependencies_set_dsPackages(add = "dsBase", client = "dsBaseClient"),
                           "No dependencies.R found in the project, so it was not updated.")
  testthat::expect_null(res)
  testthat::expect_false(file.exists(file.path(project, "dependencies.R")))
})

test_that("internal_dependencies_set_dsPackages appends a new block at the end of a dependencies.R without a block and without the bot marker", {
  project <- withr::local_tempdir()
  testthat::local_mocked_bindings(here = function(...) file.path(project, ...), .package = "here")
  writeLines(c("library(here)", "library(dplyr)"), file.path(project, "dependencies.R"))
  res <- dsAnalysis:::internal_dependencies_set_dsPackages(add = "dsBase", client = "dsBaseClient")
  lines <- readLines(file.path(project, "dependencies.R"))
  testthat::expect_identical(lines[1:2], c("library(here)", "library(dplyr)"))
  testthat::expect_identical(lines[3], "")
  testthat::expect_true("library(dsBase); library(dsBaseClient)" %in% lines)
  testthat::expect_identical(lines[length(lines) - 1], "library(dsBase); library(dsBaseClient)")
  testthat::expect_identical(res$server, "dsBase")
  testthat::expect_identical(res$client, "dsBaseClient")
  testthat::expect_identical(nrow(res), 1L)
})

test_that("internal_dependencies_set_dsPackages writes a package without a client as a single library() call", {
  project <- withr::local_tempdir()
  testthat::local_mocked_bindings(here = function(...) file.path(project, ...), .package = "here")
  writeLines(c("library(here)"), file.path(project, "dependencies.R"))
  res <- dsAnalysis:::internal_dependencies_set_dsPackages(add = "dsBase", client = "")
  lines <- readLines(file.path(project, "dependencies.R"))
  testthat::expect_true("library(dsBase)" %in% lines)
  testthat::expect_false(any(grepl("library(dsBase);", lines, fixed = TRUE)))
  testthat::expect_identical(res$server, "dsBase")
  testthat::expect_identical(nrow(res), 1L)
})

test_that("internal_dependencies_set_dsPackages inserts a new block before the bot marker line", {
  project <- withr::local_tempdir()
  testthat::local_mocked_bindings(here = function(...) file.path(project, ...), .package = "here")
  bot_marker <- "#### bot-suggest: packages (updated by datashield-analysis-suggest)"
  writeLines(c("library(here)", bot_marker, "library(somethingElse)"), file.path(project, "dependencies.R"))
  dsAnalysis:::internal_dependencies_set_dsPackages(add = "dsSurvival", client = "dsSurvivalClient")
  lines <- readLines(file.path(project, "dependencies.R"))
  marker_line <- which(lines == bot_marker)
  lib_line <- which(lines == "library(dsSurvival); library(dsSurvivalClient)")
  testthat::expect_length(marker_line, 1L)
  testthat::expect_length(lib_line, 1L)
  testthat::expect_true(lib_line < marker_line)
  testthat::expect_identical(lines[1], "library(here)")
  testthat::expect_identical(lines[length(lines)], "library(somethingElse)")
})

test_that("internal_dependencies_set_dsPackages replaces an existing block in place and keeps the lines around it", {
  project <- withr::local_tempdir()
  testthat::local_mocked_bindings(here = function(...) file.path(project, ...), .package = "here")
  writeLines(c("library(here)"), file.path(project, "dependencies.R"))
  dsAnalysis:::internal_dependencies_set_dsPackages(add = "dsBase", client = "dsBaseClient")
  lines_before <- readLines(file.path(project, "dependencies.R"))
  res <- dsAnalysis:::internal_dependencies_set_dsPackages(add = "dsSurvival", client = "dsSurvivalClient")
  lines <- readLines(file.path(project, "dependencies.R"))
  testthat::expect_identical(lines[1], "library(here)")
  testthat::expect_true("library(dsBase); library(dsBaseClient)" %in% lines)
  testthat::expect_true("library(dsSurvival); library(dsSurvivalClient)" %in% lines)
  testthat::expect_identical(nrow(res), 2L)
  testthat::expect_setequal(res$server, c("dsBase", "dsSurvival"))
  testthat::expect_identical(length(lines), length(lines_before) + 1L)
})

test_that("internal_dependencies_set_dsPackages removes a recorded package from the block and from the returned data frame", {
  project <- withr::local_tempdir()
  testthat::local_mocked_bindings(here = function(...) file.path(project, ...), .package = "here")
  writeLines(c("library(here)"), file.path(project, "dependencies.R"))
  dsAnalysis:::internal_dependencies_set_dsPackages(add = c("dsBase", "dsSurvival"), client = c("dsBaseClient", "dsSurvivalClient"))
  res <- dsAnalysis:::internal_dependencies_set_dsPackages(remove = "dsBase")
  lines <- readLines(file.path(project, "dependencies.R"))
  testthat::expect_false("library(dsBase); library(dsBaseClient)" %in% lines)
  testthat::expect_true("library(dsSurvival); library(dsSurvivalClient)" %in% lines)
  testthat::expect_identical(nrow(res), 1L)
  testthat::expect_identical(res$server, "dsSurvival")
})

test_that("internal_dependencies_set_dsPackages re-adding a recorded package updates its client without duplicating the entry", {
  project <- withr::local_tempdir()
  testthat::local_mocked_bindings(here = function(...) file.path(project, ...), .package = "here")
  writeLines(c("library(here)"), file.path(project, "dependencies.R"))
  dsAnalysis:::internal_dependencies_set_dsPackages(add = "dsBase", client = "dsBaseClient")
  res <- dsAnalysis:::internal_dependencies_set_dsPackages(add = "dsBase", client = "")
  lines <- readLines(file.path(project, "dependencies.R"))
  testthat::expect_identical(nrow(res), 1L)
  testthat::expect_identical(res$server, "dsBase")
  testthat::expect_identical(res$client, "")
  testthat::expect_true("library(dsBase)" %in% lines)
  testthat::expect_false("library(dsBase); library(dsBaseClient)" %in% lines)
  testthat::expect_length(which(grepl("library(dsBase", lines, fixed = TRUE)), 1L)
})

test_that("internal_dependencies_set_dsPackages adds several packages at once in the order given", {
  project <- withr::local_tempdir()
  testthat::local_mocked_bindings(here = function(...) file.path(project, ...), .package = "here")
  writeLines(c("library(here)"), file.path(project, "dependencies.R"))
  res <- dsAnalysis:::internal_dependencies_set_dsPackages(add = c("dsBase", "dsSurvival"), client = c("dsBaseClient", ""))
  lines <- readLines(file.path(project, "dependencies.R"))
  testthat::expect_identical(res$server, c("dsBase", "dsSurvival"))
  testthat::expect_identical(res$client, c("dsBaseClient", ""))
  first <- which(lines == "library(dsBase); library(dsBaseClient)")
  second <- which(lines == "library(dsSurvival)")
  testthat::expect_length(first, 1L)
  testthat::expect_length(second, 1L)
  testthat::expect_identical(second, first + 1L)
})

test_that("internal_dependencies_set_dsPackages leaves the file round-trippable so a second call reads back the same packages", {
  project <- withr::local_tempdir()
  testthat::local_mocked_bindings(here = function(...) file.path(project, ...), .package = "here")
  writeLines(c("library(here)"), file.path(project, "dependencies.R"))
  written <- dsAnalysis:::internal_dependencies_set_dsPackages(add = c("dsBase", "dsSurvival"), client = c("dsBaseClient", "dsSurvivalClient"))
  recorded <- dsAnalysis:::internal_dependencies_dsPackages(readLines(file.path(project, "dependencies.R")))
  testthat::expect_identical(recorded$server, c("dsBase", "dsSurvival"))
  testthat::expect_identical(recorded$client, c("dsBaseClient", "dsSurvivalClient"))
  testthat::expect_identical(nrow(recorded), nrow(written))
})
