name: extracting metadata information from repo and forwarding to central repository

on:
  push:
    branches: [main, master]
    paths:
      - R/*

  pull_request:
    branches: [main, master]
    paths:
      - R/*

jobs:
  extract_information:
    uses: FlorianSchw/datashield-workflows/.github/workflows/datashield_function_metadata_extraction.yaml@master

  pushing_extracted_information:
    needs: extract_information
    if: needs.extract_information.outputs.output1 == 'true'
    uses: FlorianSchw/datashield-workflows/.github/workflows/datashield_function_metadata_fwd.yaml@master
    with:
      user_name: ${{ github.actor }}
      user_email: ${{ github.actor }}@users.noreply.github.com
    secrets: inherit
