name: extracting metadata informtion

on:
  push:
    branches: [main, master]
    paths:
      - R/*

  pull_request:
    branches: [main, master]
    paths:
      - R/*

jobs:
  Extract_Information:
    uses: FlorianSchw/dsDemo/.github/workflows/datashield_functions_metadata2.yaml@master

  Pushing_Extracted_Information:
    needs: Extract_Information
    if: needs.Extract_Information.outputs.output1 == 'true'
    uses: FlorianSchw/dsDemo/.github/workflows/datashield_functions_metadata3.yaml@master
    with:
      user_name: $GITHUB_ACTOR
      user_email: ${GITHUB_ACTOR}@users.noreply.github.com
    secrets: inherit
