name: R-CMD-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 7 * * *'
  workflow_dispatch:

jobs:
  check:
    uses: FlorianSchw/package-workflows/.github/workflows/r-cmd-check.yml@main
    with:
      r-version-list: '["release", "4.4.3"]'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  keepalive:
    if: github.event_name == 'schedule'
    permissions:
      actions: write
    uses: FlorianSchw/package-workflows/.github/workflows/workflow-keepalive.yml@main
